### ISSUE TITLE
Training 

### ISSUE THREAD

**Issue by rainofmine** [mingyuan-zhang/MotionDiffuse#7]
I run the training code on a single GPU but it seems to have Nan value. Is anything Wrong?

![6345F08F-AD73-4CA2-941D-BC77A23B2077](https://user-images.githubusercontent.com/32377591/196397215-367d12ec-3f55-4783-b176-fc8af9f6d176.png)

**Comment by mingyuan-zhang** [comment]
Hi, may you share more details (logs, commands, etc)?

**Comment by rainofmine** [comment]
@mingyuan-zhang 

- Ubuntu 18.04
- CUDA 10.1
- Pytorch 1.8.2

I just run the provided script
`PYTHONPATH="$(dirname $0)/..":$PYTHONPATH \
python -u tools/train.py \
    --name t2m_sample \
    --batch_size 128 \
    --times 200 \
    --num_epochs 50 \
    --dataset_name t2m`

The logs
`[2022-10-18 17:27:40,995.995 dsw42613-688cbd5b8d-fvj7q:2331 INFO utils.py:30] NOTICE: PAIDEBUGGER is turned off.
[2022-10-18 17:27:42,717.717 dsw42613-688cbd5b8d-fvj7q:2331 INFO font_manager.py:1423] Generating new fontManager, this may take some time...
------------ Options -------------
batch_size: 128
checkpoints_dir: ./checkpoints
dataset_name: t2m
decomp_name: Decomp_SP001_SM001_H512
diffusion_steps: 1000
dim_att_vec: 512
dim_dec_hidden: 1024
dim_movement_dec_hidden: 512
dim_movement_enc_hidden: 512
dim_movement_latent: 512
dim_pos_hidden: 1024
dim_pri_hidden: 1024
dim_text_hidden: 512
dim_z: 128
distributed: False
estimator_mod: bigru
eval_every_e: 5
feat_bias: 5
gpu_id: -1
is_continue: False
is_train: True
latent_dim: 512
log_every: 50
lr: 0.0002
max_text_len: 20
n_layers_dec: 1
n_layers_pos: 1
n_layers_pri: 1
name: t2m_sample
no_clip: False
no_eff: False
num_epochs: 50
num_layers: 8
save_every_e: 5
save_latest: 500
text_enc_mod: bigru
times: 200
unit_length: 4
-------------- End ----------------
100%|███████████████████████████████████████| 338M/338M [00:06<00:00, 53.1MiB/s]
100%|████████████████████████████████████████████████████████████| 23384/23384 [11:02<00:00, 35.32it/s]
Cannot get the env variable of GPU_STATUS_FILE, no data report to scheduler. This is not an error. It is because the scheduler of the cluster did not enable this feature.

[W python_anomaly_mode.cpp:104] Warning: Error detected in MseLossBackward. Traceback of forward call that caused the error:
  File "tools/train.py", line 89, in <module>
    trainer.train(train_dataset)
  File "/mnt/workspace/project/MotionDiffuse/text2motion/trainers/ddpm_trainer.py", line 202, in train
    log_dict = self.update()
  File "/mnt/workspace/project/MotionDiffuse/text2motion/trainers/ddpm_trainer.py", line 140, in update
    loss_logs = self.backward_G()
  File "/mnt/workspace/project/MotionDiffuse/text2motion/trainers/ddpm_trainer.py", line 130, in backward_G
    loss_mot_rec = self.mse_criterion(self.fake_noise, self.real_noise).mean(dim=-1)
  File "/home/pai/lib/python3.6/site-packages/easyacc/paidebug_hook/pytorch/module.py", line 19, in decorated
    return f(*args, **kwargs)
  File "/home/pai/lib/python3.6/site-packages/torch/nn/modules/module.py", line 905, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pai/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 528, in forward
    return F.mse_loss(input, target, reduction=self.reduction)
  File "/home/pai/lib/python3.6/site-packages/torch/nn/functional.py", line 2929, in mse_loss
    return torch._C._nn.mse_loss(expanded_input, expanded_target, _Reduction.get_enum(reduction))
 (function _print_stack)
Traceback (most recent call last):
  File "tools/train.py", line 89, in <module>
    trainer.train(train_dataset)
  File "/mnt/workspace/project/MotionDiffuse/text2motion/trainers/ddpm_trainer.py", line 202, in train
    log_dict = self.update()
  File "/mnt/workspace/project/MotionDiffuse/text2motion/trainers/ddpm_trainer.py", line 141, in update
    self.loss_mot_rec.backward()
  File "/home/pai/lib/python3.6/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/pai/lib/python3.6/site-packages/torch/autograd/__init__.py", line 147, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: Function 'MseLossBackward' returned nan values in its 0th output.`

**Comment by mingyuan-zhang** [comment]
Can you print the batchsize of this iteration? It seems that there is no data given to pipeline. The mean value of an empty array is NaN.

**Comment by rainofmine** [comment]
@mingyuan-zhang 

I found that the predicted fake noise increases gradually and becomes Nan in a few steps. 

The left is real noise. The right is fake noise.
![image](https://user-images.githubusercontent.com/32377591/196634801-f28fedd6-e85f-4ac8-b45e-16729494006d.png)

**Comment by mingyuan-zhang** [comment]
I tried the same setting as yours but I didn't get this issue. Have you checked the validity of the processed data as in https://github.com/EricGuo5513/HumanML3D/blob/main/motion_representation.ipynb and https://github.com/EricGuo5513/HumanML3D/blob/main/cal_mean_variance.ipynb

**Comment by SkyeLu** [comment]
Hi, did you solve this problem? I meet the same problem, the predicted fake noise becomes NaN in a few steps while training on the HumanML3D dataseat.
